# Generated by Django 6.0.4 on 2026-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('S', 'Mała'), ('M', 'Średnia'), ('L', 'Duża')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
